config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  get '/auth/github' => 'auth#github'
  get '/auth/github/callback' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/organizations' => 'organizations#index', :as => 'organizations'
  get '/organizations/:organization' => 'organizations#show', :as => 'organization', :constraints  => { :organization => /[-0-z\._]+/ }
  get '/organizations/:organization/repos/:repo' => 'repos#show', :as => 'repo', :constraints  => { :repo => /[-0-z\._]+/, :organization => /[-0-z\._]+/ }
end

app/models/github_connection.rb
class GithubConnection
  attr_reader :orgs, :repos, :issues, :username, :token

  def initialize(github_data)
    @username = github_data["username"]
    @token = github_data["token"]
  end

  def get_organizations
    orgs = json_parse("https://api.github.com/user/orgs", "login")
  end

  def get_repos(organization)
    repos = json_parse("https://api.github.com/orgs/#{organization}/repos", "name")
  end

  def get_issues(organization, repo)
    issues = json_parse("https://api.github.com/repos/#{organization}/#{repo}/issues")
  end

  def make_request(url, header)
    request = Typhoeus::Request.new(url, header)
    response = request.run
  end

  def json_parse(url, key = nil)
    JSON.parse(make_request(url, headers: {Authorization: "token #{token}"}).body).map do |to_parse| 
      key ? to_parse[key] : to_parse
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :github_connection, only: [:index, :show]

  def index
    @username = @github.username
    @organizations = @github.get_organizations
  end

  def show
    @organization = params[:organization]
    @repos = @github.get_repos(@organization)
  end

  private
  def github_connection
    @github = GithubConnection.new(session['github'])
  end

end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  before_action :github_connection, only: [:show]

  #TODO have this show page rendered via ajax upon clicking on individual repo (like a toggle feature?)
  def show
    @repo = params[:repo]
    @organization = params[:organization]
    @issues = @github.get_issues(@organization, @repo)
    respond_to do |format|
      format.js
    end
  end

  private
  def github_connection
    @github = GithubConnection.new(session['github'])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    set_session_data

    if session['github'][:token]
      redirect_to organizations_path
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end

  private
    def set_session_data
      github_data = request.env['omniauth.auth']
      session['github'] = {
        :uid => github_data.uid,
        :username => github_data.info.nickname,
        :email => github_data.info.email,
        :token => github_data.credentials.token
      }
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/repos_helper.rb
module ReposHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if session['github'] %>
          <li><%= link_to "Log Out", logout_path, method: :delete %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Issues Roster</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
</head>
<body>

<%= render 'layouts/header' %>

<%= yield %>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/organizations/index.html.erb
<h1><%= @username %>'s Organizations</h1>

<% @organizations.each do |organization| %>
  <%= link_to organization, organization_path(:organization => organization) %><br>
<% end %>

app/views/organizations/show.html.erb
<h1> <%= @organization %> Repos </h1>

<% @repos.each do |repo| %>
  <div id="eachrepo">
    <%= link_to repo, repo_path(:repo => repo), :data => repo, :remote => true %><br>
    <div id="appendhere"></div>
  </div>
<% end %>

app/views/repos/_repo.html.erb
<div class="all-issues">
  <% if !@issues.empty? %>
    <% @issues.each do |issue|  %>
      <ul>
        <li><strong>Issue: <%= link_to issue["title"], issue["html_url"], :target => "_blank" %></strong></li>
        <li>Submitted by: <%= link_to issue["user"]["login"], issue["user"]["html_url"], :target => "_blank" %></li>
        <li>Date: <%= DateTime.parse(issue["created_at"]).to_formatted_s(:long) %></li>
        <li>Status: <%= issue["state"] %></li>
      <% if !issue["labels"].empty? %>
        <li>Labels: <%= issue["labels"][0]["name"] %></li>
      <% end %>
      </ul>
    <% end %>
  <% else %>
    <p><strong>There are no issues currently on this repo.</strong></p>
  <% end %>
</div>

app/views/repos/show.js.erb
$('#appendhere').append('<%= escape_javascript(render :partial => "repo") %>').slideToggle("slow");

//TODO: remove the :remote => true and render with .get() and pass data attribute info